[package]
name = "vertx"
version = "0.1.0"
authors = ["Pierre Zemb <contact@pierrezemb.fr>"]

[dependencies]
futures = "0.1"
tokio-core = "0.1"
tokio-service = "0.1"
tokio-proto = "0.1"
rustc-serialize = "0.3"
